name: "Destroy_TF_Deployment_Manual"

on:
  workflow_dispatch: {}

jobs:
  destroy-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up Terraform CLI credentials
        run: echo "credentials \"app.terraform.io\" { token = \"$TFC_API_TOKEN\" }" > ~/.terraformrc

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TFC_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        continue-on-error: true

      - name: Terraform Destroy Status
        if: steps.destroy.outcome == 'failure'
        run: exit 1
