name: "Destroy_TF_Deployment_Manual"

on:
  workflow_dispatch: {}

jobs:
  destroy-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

#      - name: Set up Terraform CLI credentials
#        run:
#          export TFC_API_TOKEN="${{ secrets.TFC_API_TOKEN }}"
      

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TFC_API_TOKEN }}

      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true

      - name: Destroy resources jobs
        id: destroy
        run: terraform destroy -auto-approve

      - name: Terraform Destroy Status
        if: steps.destroy.outcome == 'failure'
        run: exit 1
