name: "Destroy_TF_Deployment_Manual"

on:
  workflow_dispatch: {}

jobs:
  destroy-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0


      - name: Terraform Init
        id: init
        run: terraform init
        with:
          terraform_version: ${{ inputs.tf_version }}
          cli_config_credentials_token: ${{ secrets.cli_config_credentials_token }}

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        continue-on-error: true

      - name: Terraform Destroy Status
        if: steps.destroy.outcome == 'failure'
        run: exit 1
